spring:
  application:
    name: videochat
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./data/videochat
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      cache:
        period: 0
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
server:
  port: 9443